//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerPower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medewerker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medewerker()
        {
            this.bestelling = new HashSet<bestelling>();
        }
    
        public int medewerkerid { get; set; }
        public string voorletters { get; set; }
        public string tussenvoegsels { get; set; }
        public string achternaam { get; set; }
        public int vestigingid { get; set; }
        public Nullable<bool> actief { get; set; }
        public string AspNetUserID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bestelling> bestelling { get; set; }
        public virtual vestiging vestiging { get; set; }
    }
}
