//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerPower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3D6D6_FlowerPowerLuukEntities : DbContext
    {
        public DB_A3D6D6_FlowerPowerLuukEntities()
            : base("name=DB_A3D6D6_FlowerPowerLuukEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artikel> artikel { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<bestelling> bestelling { get; set; }
        public virtual DbSet<klant> klant { get; set; }
        public virtual DbSet<medewerker> medewerker { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<vestiging> vestiging { get; set; }
    }
}
